#!/usr/bin/env bash
# Fetch + fingerprint-verify the pinned relay root CAs, then emit the .pem.inc files
# that firmware/src/ca_bundle.h includes when CA_BUNDLE_POPULATED=1.
#
# WHY a script (not hand-typed PEM): a corrupted/typo'd root silently fails to parse in
# mbedTLS → the device refuses every relay handshake (fail-closed, by design). The only
# safe way to get the exact bytes is to pull the CA's PUBLISHED root and verify its
# SHA-256 fingerprint against the value baked into this script. No network trust is
# assumed: even if the download is MITM'd, a wrong fingerprint aborts the build.
#
# Usage:
#   firmware/scripts/fetch_ca_bundle.sh            # fetch, verify, write src/ca/*.pem.inc
#   firmware/scripts/fetch_ca_bundle.sh --check     # verify existing .pem.inc only (CI)
#
# The committed roots are the DEFAULT trust anchor for a relay build: [env:relay] in
# platformio.ini compiles with CA_BUNDLE_POPULATED=1 by default (ca_bundle.h sets it for any
# RELAY_MODE image), so `pio run -e relay` links these roots out of the box. Re-run this script
# only to refresh the roots (CA rotation) or to re-verify them in CI (--check).
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$(cd "$HERE/../src" && pwd)"
CA_DIR="$SRC/ca"
mkdir -p "$CA_DIR"

# name | published-download-URL | expected SHA-256 fingerprint (colon-separated, upper)
# Fingerprints are the CAs' published root fingerprints; they are the trust anchor of THIS
# script. Changing a fingerprint here is an explicit, reviewable trust decision.
ROOTS=(
  "isrg_root_x1|https://letsencrypt.org/certs/isrgrootx1.pem|96:BC:EC:06:26:49:76:F3:74:60:77:9A:CF:28:C5:A7:CF:E8:A3:C0:AA:E1:1A:8F:FC:EE:05:C0:BD:DF:08:C6"
  "digicert_global_root_g2|https://cacerts.digicert.com/DigiCertGlobalRootG2.crt.pem|CB:3C:CB:B7:60:31:E5:E0:13:8F:8D:D3:9A:23:F9:DE:47:FF:C3:5E:43:C1:14:4C:EA:27:D4:6A:5A:B1:CB:5F"
  "baltimore_cybertrust_root|https://cacerts.digicert.com/BaltimoreCyberTrustRoot.crt.pem|16:AF:57:A9:F6:76:B0:AB:12:60:95:AA:5E:BA:DE:F2:2A:B3:11:19:D6:44:AC:95:CD:4B:93:DB:F3:F2:6A:EB"
)

fingerprint() { openssl x509 -in "$1" -noout -fingerprint -sha256 | sed 's/^.*=//'; }

CHECK_ONLY=0
[[ "${1:-}" == "--check" ]] && CHECK_ONLY=1

fail=0
for entry in "${ROOTS[@]}"; do
  IFS='|' read -r name url want <<<"$entry"
  pem="$CA_DIR/$name.pem"
  inc="$CA_DIR/$name.pem.inc"

  if [[ "$CHECK_ONLY" == 1 ]]; then
    [[ -f "$pem" ]] || { echo "MISSING $pem (run without --check first)"; fail=1; continue; }
  else
    echo "fetch  $name <- $url"
    curl -fsSL "$url" -o "$pem"
  fi

  got="$(fingerprint "$pem")"
  if [[ "$got" != "$want" ]]; then
    echo "FINGERPRINT MISMATCH for $name"
    echo "  want $want"
    echo "  got  $got"
    fail=1
    continue
  fi
  echo "verify $name SHA-256 OK"

  if [[ "$CHECK_ONLY" == 0 ]]; then
    # Emit a C string literal include: a raw-string PEM the compiler concatenates verbatim.
    {
      echo "// generated by fetch_ca_bundle.sh — do not edit; re-run the script to refresh"
      printf 'R"PEM(\n'
      cat "$pem"
      printf ')PEM"\n'
    } >"$inc"
    echo "write  $inc"
  fi
done

if [[ "$fail" != 0 ]]; then
  echo "ABORT: at least one root failed verification — ca_bundle NOT populated."
  exit 1
fi

echo
echo "All pinned roots verified. These are the DEFAULT relay trust anchor:"
echo "'pio run -e relay' links them automatically (CA_BUNDLE_POPULATED defaults to 1 for a"
echo "RELAY_MODE build). No extra flag needed."
